apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  ConnectionStrings__FIAPGamesConnection: "Server=sqlserver-auth,1433;Database=fiapgames_auth;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True"
  Jwt__Key: "ChaveSuperSecretaFiapGamesEAD12MuitoLongaParaGarantirSeguranca123!"
  RabbitMq__Password: "guest"
